### ISSUE TITLE
G2Engine.addRecordWithInfo doesn't respect flags

### ISSUE THREAD

**Issue by glennjdea** [Senzing/g2-sdk-python#128]
According to the [docs](https://docs.senzing.com/python/senzing-G2Engine-reference.html#addRecordWithInfo) , the flags argument are "Control flags for specifying what data about the entity to retrieve".  I've tried all sorts of values from https://senzing.zendesk.com/hc/en-us/articles/360057088853-G2Command-Flag-Values, but none seem to have any effect.

I'd like the JSON returned to include the IDs of any related entities, so I tried G2_EXPORT_INCLUDE_ALL_RELATIONSHIPS and G2_ENTITY_INCLUDE_ALL_RELATIONS.

**Comment by brianmacy** [comment]
addRecordWithInfo only returns affected entity ids.  What you are looking for is the getEntityByRecordID function.

**Comment by glennjdea** [comment]
Hi @docktermj .
1. version 2.8.7
2. I'm using flag values from https://senzing.zendesk.com/hc/en-us/articles/360057088853-G2Command-Flag-Values
3. I'm using a keyword arg for the flags (see below).

```
    g2_engine.purgeRepository();
    f = 30
    with open("test_data/scenario_1_t0.json", 'r') as records:
        for record in records:
            g2_engine.addRecordWithInfo("PEOPLE",json.loads(str(record))['RECORD_ID'],record,response_bytearray,flags=f)
            print(json.loads(response_bytearray.decode("utf-8")))
    with open("test_data/scenario_1_t1.json", 'r') as records:
        for record in records:
            g2_engine.addRecordWithInfo("PEOPLE",json.loads(str(record))['RECORD_ID'],record,response_bytearray,flags=f)
            print(json.loads(response_bytearray.decode("utf-8")))
    with open("test_data/scenario_1_t2.json", 'r') as records:
        for record in records:
            g2_engine.addRecordWithInfo("PEOPLE",json.loads(str(record))['RECORD_ID'],record,response_bytearray,flags=f)
            print(json.loads(response_bytearray.decode("utf-8")))
    with open("test_data/scenario_1_t3.json", 'r') as records:
        for record in records:
            g2_engine.addRecordWithInfo("PEOPLE",json.loads(str(record))['RECORD_ID'],record,response_bytearray,flags=f)
            print(json.loads(response_bytearray.decode("utf-8")))

```
```
{'DATA_SOURCE': 'PEOPLE', 'RECORD_ID': 'ALICE_1', 'AFFECTED_ENTITIES': [{'ENTITY_ID': 1, 'LENS_CODE': 'DEFAULT'}], 'INTERESTING_ENTITIES': []}
{'DATA_SOURCE': 'PEOPLE', 'RECORD_ID': 'JEFF_1', 'AFFECTED_ENTITIES': [{'ENTITY_ID': 2, 'LENS_CODE': 'DEFAULT'}], 'INTERESTING_ENTITIES': []}
{'DATA_SOURCE': 'PEOPLE', 'RECORD_ID': 'ALICE_2', 'AFFECTED_ENTITIES': [{'ENTITY_ID': 1, 'LENS_CODE': 'DEFAULT'}], 'INTERESTING_ENTITIES': []}
{'DATA_SOURCE': 'PEOPLE', 'RECORD_ID': 'ALICE_3', 'AFFECTED_ENTITIES': [{'ENTITY_ID': 4, 'LENS_CODE': 'DEFAULT'}], 'INTERESTING_ENTITIES': []}
{'DATA_SOURCE': 'PEOPLE', 'RECORD_ID': 'BOB_1', 'AFFECTED_ENTITIES': [{'ENTITY_ID': 5, 'LENS_CODE': 'DEFAULT'}], 'INTERESTING_ENTITIES': []}
{'DATA_SOURCE': 'PEOPLE', 'RECORD_ID': 'ALICE_4', 'AFFECTED_ENTITIES': [{'ENTITY_ID': 1, 'LENS_CODE': 'DEFAULT'}, {'ENTITY_ID': 4, 'LENS_CODE': 'DEFAULT'}], 'INTERESTING_ENTITIES': []}
{'DATA_SOURCE': 'PEOPLE', 'RECORD_ID': 'BOB_2', 'AFFECTED_ENTITIES': [{'ENTITY_ID': 5, 'LENS_CODE': 'DEFAULT'}], 'INTERESTING_ENTITIES': []}
```
Record BOB_2 establishes a relationship between 5 and 2.
![image](https://user-images.githubusercontent.com/107553312/175547798-cd6bdd02-ccfb-49ff-8915-587846c7e14c.png)

**Comment by docktermj** [comment]
@glennjdea Given you request:
> I'd like the JSON returned to include the IDs of any related entities,

I think @brianmacy, two posts up, is on the right track for answering your question.  The `addRecordWithInfo()` method return *affected* entity IDs.  What you seem to be seeking is *related* Entity IDs.  @brianmacy Suggests `getEntityByRecordID()` to get what you want.

**Comment by docktermj** [comment]
@ryanbasile,  Can you review the documentation for clarification on this issue?

**Comment by docktermj** [comment]
@glennjdea We've opened up https://github.com/Senzing/senzing-sdk-api-specification/issues/34 to address the issue with the documentation.

**Comment by docktermj** [comment]
@glennjdea As we are fixing the documentation, is there anything else we can help with on your original issue?

**Comment by glennjdea** [comment]
Many thanks @docktermj.  Is it worth clarifying the comments in the source to make it clear that the arg has no effect?

https://github.com/Senzing/g2-sdk-python/blob/main/src/senzing/G2Engine.py#L727
https://github.com/Senzing/g2-sdk-python/blob/main/src/senzing/G2Engine.py#L749
https://github.com/Senzing/g2-sdk-python/blob/main/src/senzing/G2Engine.py#L560

I guess "reserved for future use" is ok as it implies that it doesn't currently do anything, but "Bitwise control flags" does kind of sound like it might do something.
