### ISSUE TITLE
Modules init() functions not explicitly map a -1 RC from engine to an exception class

### ISSUE THREAD

**Issue by antaenc** [Senzing/g2-sdk-python#134]
Currently init functions - e.g G2Engine -> init() raises an explicit exception class if the engine returns -1. This prevents catching the license has expired exception, as an example. Change (only) the module init functions to use the mapping in G2Exception to enable capturing specific exceptions. Only the init functions need this, a -1 check on other functions is valid as it means the object isn't initialised.

Consideration needs to be given if this is backwards breaking and would need to go in V4. 

```
if ret_code == -1:
    raise G2ModuleNotInitialized('G2Engine has not been successfully initialized')
elif ret_code < 0:
    self._lib_handle.G2_getLastException(tls_var.buf, sizeof(tls_var.buf))
    raise TranslateG2ModuleException(tls_var.buf.value)
```

to:

if ret_code != 0:
    self._lib_handle.G2_getLastException(tls_var.buf, sizeof(tls_var.buf))
    raise TranslateG2ModuleException(tls_var.buf.value)

**Comment by jamietypovsky** [comment]
return code should be less than 0.
